import os
os.system('cls')

#MULTIPLICAÇÃO
print('==TABUADA==')
tabuada = int(input('Digite um número: '))
for i in range(1, 11):
    print(f'{tabuada} x {i} = {tabuada * i}')

#SUBTRAÇÃO
print('==SUBTRAÇÃO==')
tabuada = int(input('Digite um número: '))
for i in range(1, 11):
    print(f'{tabuada} - {i} = {tabuada - i}')

#SOMA
print('==SOMA==')
tabuada = int(input('Digite um número: '))
for i in range(1, 11):
    print(f'{tabuada} + {i} = {tabuada + i}')

#DIVISÃO
print('==DIVISÃO==')
tabuada = int(input('Digite um número: '))
for i in range(1, 11):
    print(f'{tabuada} / {i} = {tabuada / i}')



print('==TABUADA==')
tabuada = int(input('Digite um número: '))
for i in range(1, 11):
    print(f'{tabuada} / {i} = {tabuada / i}')

