import os
os.system('cls')

print('==TABUADA==')
tabuada = int(input('Digite um número: '))
    print(f'{tabuada} x {i} = {tabuada * i}')


print('==TABUADA==')
tabuada = int(input('Digite um número: '))
    print(f'{tabuada} - {i} = {tabuada - i}')


print('==TABUADA==')
tabuada = int(input('Digite um número: '))
for i in range(1, 11):
    print(f'{tabuada} + {i} = {tabuada + i}')


print('==TABUADA==')
tabuada = int(input('Digite um número: '))
for i in range(1, 11):
    print(f'{tabuada} / {i} = {tabuada / i}')

