import os
os.system('cls')


while True:
    numeros = int(input('Digite os valores: '))
    if pares % 2 == 0:
        pares = % 2 == 0
        pares = (print(f'Pares: {pares}'))
    if pares % 2 == 1:
        impares =  print(f'Ímpares: {pares}')
    if pares == 0:
        print('Programa encerrado.')
        print()
        print(f'Quantidade de números pares: {pares}')
        print(f'Quantidade de números ímpares: {impares}')
        break